# Generated by Django 5.1.1 on 2024-09-26 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profilemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(default='/profile/default.jpg', upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
