# Generated by Django 5.1.1 on 2024-09-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogmate_app', '0002_postmodel_author_postmodel_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-date_created',)},
        ),
    ]
